# Generated by Django 2.2.1 on 2020-08-18 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareRes', '0002_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_keyword',
            field=models.CharField(max_length=150),
        ),
    ]
